server:
  port: 8084
  servlet:
    context-path: /ai

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/ai-service?authSource=admin
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
    vertex:
      ai:
        embedding:
          credentials-uri: embedding.json
          project-id: "big-booking-446612-s2"
          location: "us-central1"
          text:
            model: text-embedding-004


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}